### ISSUE TITLE
A little doubt

### ISSUE THREAD

**Issue by yechenzhi** [csiro-robotics/TCE#5]
https://github.com/csiro-robotics/TCE/blob/55e76ceba5d400c1698df3fb3ee072226d5a12d8/datasets/pretraining/kinetics400.py#L117

shouldn't this be  self.all_membank_negatives[:membank_idx] + self.all_membank_negatives[**membank_idx**:]?

**Comment by JBKnights** [comment]
Hello!  From what I can see, the reason for this is that this line excludes the positive example - which exists in self.all_membank_negatives at the index membank_idx - from the set of potential negatives available, since we don't want to be selecting the positive example's stored features as a negative.
